"""Add created_date, updated_date, estimate_start, estimate_end to Task

Revision ID: 69631597e04b
Revises: eed81ace5a6c
Create Date: 2025-10-16 12:00:19.389042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69631597e04b'
down_revision = 'eed81ace5a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('estimate_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estimate_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('estimate_end')
        batch_op.drop_column('estimate_start')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
